production:
  build: .
  command: rails server -p 3000 -b '0.0.0.0' -e production
  volumes:
    - .:/app
    - ../production/public/system/:/app/public/system
  ports:
    - "3000:3000"
  links:
    - mongo
  environment:
    - MONGOID_HOST=mongo
    - MONGOID_PORT=27017
    - MONGOID_DATABASE=artaround
staging:
  build: .
  command: rails server -p 3001 -b '0.0.0.0'
  volumes:
    - .:/app
    - ../staging/public/system/:/app/public/system
  ports:
    - "3001:3001"
  links:
    - mongo
  environment:
    - MONGOID_HOST=mongo
    - MONGOID_PORT=27017
    - MONGOID_DATABASE=artaround_staging
mongo:
  image: mongo:3.0
  volumes:
    - ../mongodata:/data/db
    - ../mongodumps:/backups
  ports:
    - "27017:27017"
nginx:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - 80:80
  links:
    - production
    - staging
